### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stdin' of null

### ISSUE THREAD

**Issue by NickLargey** [pndmix/atom-rampcode#4]
Hello,

Rampcode is a wonderful project, and thank you for creating it.

When I try to run any code from the cheatsheet.ramp script I get this error:

    Uncaught TypeError: Cannot read property 'stdin' of null

with the stack trace:

    TypeError: Cannot read property 'stdin' of null
        at Main.evalCode (file:///C:/Users/Clientelephone/.atom/packages/atom-rampcode/lib/main.js:54:31)
    at Main.evalRange (file:///C:/Users/Clientelephone/.atom/packages/atom-rampcode/lib/main.js:72:10)
    at file:///C:/Users/Clientelephone/.atom/packages/atom-rampcode/lib/main.js:76:41
    at Array.forEach (<anonymous>)
    at Main.evalRanges (file:///C:/Users/Clientelephone/.atom/packages/atom-rampcode/lib/main.js:76:19)
    at Main.evalLine (file:///C:/Users/Clientelephone/.atom/packages/atom-rampcode/lib/main.js:89:17)
    at HTMLElement.atomRampcodeEvalLine (file:///C:/Users/Clientelephone/.atom/packages/atom-rampcode/lib/atom-rampcode.js:42:49)
    at CommandRegistry.handleCommandEvent (C:\Users\Clientelephone\AppData\Local\atom\app-1.38.2\resources\app\static\<embedded>:11:348418)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (C:\Users\Clientelephone\AppData\Local\atom\app-1.38.2\resources\app\static\<embedded>:11:1247210)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (C:\Users\Clientelephone\AppData\Local\atom\app-1.38.2\resources\app\static\<embedded>:11:1243344)
    at WindowEventHandler.handleDocumentKeyEvent (C:\Users\Clientelephone\AppData\Local\atom\app-1.38.2\resources\app\static\<embedded>:11:283624)

I'm on Windows 10 running Atom 1.38.2 x64 and PD 0.49.0.

**Comment by pndmix** [comment]
Thanks report. Try opening the rampcode patch in PD before running toggle.

**Comment by NickLargey** [comment]
I still get the same error when opening the PD patch first, unfortunately. I tried reinstalling both PD and Atom as well, added pdsend.exe to Atom's path and the bin folder to PD's path and it appears that window's defender is set to not block PD. I am getting the error: 
    netreceive: failed to sett SO_BROADCAST
bind: Unknown error (10013)
in PD when I open it up.

This is my first time setting anything like this up in PD so your help is greatly appreciated!

**Comment by pndmix** [comment]
It is a 10013 socket error and your machine does not permit to bind a new TCP port locally. Maybe you should need to make the rampcode patch listen to the other port. Please try the following.
* Change the object `netreceive 8080` to `netreceive <new port>` in the rampcode patch
* Change the default port to new port  in this package's setting

**Comment by NickLargey** [comment]
Sorry, just getting back to this. It worked! Thank you so much for your help and patience! I've very excited to get to work!
